# -*- coding: utf-8 -*-
"""Tipos de datos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nk4H1pVKDGkPxrKzgrz_nV-rEc7auHrv
"""

import psycopg2
conn = psycopg2.connect(host="35.222.74.90",dbname="dvdrental",user="postgres", password="Welcome01")
cur = conn.cursor()
cur.execute("SELECT first_name FROM actor")  #opción SQL
print("The number of parts: ", cur.rowcount)
row = cur.fetchone()
 
while row is not None:
    print(row)
    row = cur.fetchone()
cur.close()



import requests
import json
url ="https://datos.gob.es/apidata/catalog/dataset.json"
response = requests.get(url)
json_data=json.loads(response.content)
#print(json_data)
print(json_data["result"]["items"][0]["distribution"][0]["title"])

import requests
import xml.etree.ElementTree as ET
 
url = "https://datos.gob.es/apidata/catalog/dataset.xml"
response = requests.get(url)


 
response_xml_as_string = response.content
responseXml = ET.fromstring(response_xml_as_string)
#testId = responseXml.find('data').find('testId')
print( responseXml.find("result").find("items")[0].find("distribution")[0].find("title").text)

import json
with open('rows.json') as json_file:
  data = json.load(json_file)

#print(json_file)
print(json_file["object"]["data"][14][22])

