version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: shonos_zurich
      MYSQL_DATABASE: dbshonos
      MYSQL_USER: dbshonos
      MYSQL_PASSWORD: hPl1940t
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: dbshonos
      WORDPRESS_DB_PASSWORD: dbshonos
      WORDPRESS_DB_NAME: dbshonos


volumes:
  db_data: {}
  wordpress_data: {}
